// <auto-generated />
namespace TestPlanViewer
{
    partial class PlanUI
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                if (connection != null)
                {
                    connection.Dispose();
                }
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PlanUI));
            this.GetResultsButton = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.PassedTotal = new System.Windows.Forms.Label();
            this.OtherTotal = new System.Windows.Forms.Label();
            this.InconclusiveTotal = new System.Windows.Forms.Label();
            this.QueuedTotal = new System.Windows.Forms.Label();
            this.BlockedTotal = new System.Windows.Forms.Label();
            this.FailedTotal = new System.Windows.Forms.Label();
            this.SaveButton = new System.Windows.Forms.Button();
            this.StructureView = new System.Windows.Forms.TreeView();
            this.UpdateResultsContextMenuStrip = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.GetResultsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ExportToExcelToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.imageList = new System.Windows.Forms.ImageList(this.components);
            this.statusStrip = new System.Windows.Forms.StatusStrip();
            this.ToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.ToolStripStatusBusy = new System.Windows.Forms.ToolStripStatusLabel();
            this.ToolStripStatusLabelSpring = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusUpdatedLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.ToolStripStatusLastUpdate = new System.Windows.Forms.ToolStripStatusLabel();
            this.SplitContainer = new System.Windows.Forms.SplitContainer();
            this.SelectedGroupBox = new System.Windows.Forms.GroupBox();
            this.ActiveSelectedLabel = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.NotExecutedSelectedLabel = new System.Windows.Forms.Label();
            this.label21 = new System.Windows.Forms.Label();
            this.label23 = new System.Windows.Forms.Label();
            this.TotalSelectedLabel = new System.Windows.Forms.Label();
            this.label25 = new System.Windows.Forms.Label();
            this.label26 = new System.Windows.Forms.Label();
            this.label27 = new System.Windows.Forms.Label();
            this.InconclusiveSelectedLabel = new System.Windows.Forms.Label();
            this.QueuedSelectedLabel = new System.Windows.Forms.Label();
            this.OtherSelectedLabel = new System.Windows.Forms.Label();
            this.label31 = new System.Windows.Forms.Label();
            this.label32 = new System.Windows.Forms.Label();
            this.FailedSelectedLabel = new System.Windows.Forms.Label();
            this.label34 = new System.Windows.Forms.Label();
            this.PassedSelectedLabel = new System.Windows.Forms.Label();
            this.BlockedSelectedLabel = new System.Windows.Forms.Label();
            this.SwitchPlanButton = new System.Windows.Forms.Button();
            this.NoDupsGroupBox = new System.Windows.Forms.GroupBox();
            this.ActiveNonDupLabel = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.NeverExecutedNonDupLabel = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.TotalNonDupLabel = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.InconclusiveNonDupLabel = new System.Windows.Forms.Label();
            this.QueuedNonDupLabel = new System.Windows.Forms.Label();
            this.OtherNonDupLabel = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.FailedNonDupLabel = new System.Windows.Forms.Label();
            this.label22 = new System.Windows.Forms.Label();
            this.PassedNonDupLabel = new System.Windows.Forms.Label();
            this.BlockedNonDupLabel = new System.Windows.Forms.Label();
            this.DupsGroupBox = new System.Windows.Forms.GroupBox();
            this.ActiveTotal = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.TotalLabel = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.NeverExecuted = new System.Windows.Forms.Label();
            this.ResultsListView = new System.Windows.Forms.ListView();
            this.OutcomeHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.StateHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.IDHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.NameHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.PathHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.PriorityHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.CompletedHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.IsAutomatedHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.TestCaseAreaHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.FailureHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.ErrorMessageHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.HistoricHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.ConfigHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.UpdateResultsContextMenuStrip.SuspendLayout();
            this.statusStrip.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.SplitContainer)).BeginInit();
            this.SplitContainer.Panel1.SuspendLayout();
            this.SplitContainer.Panel2.SuspendLayout();
            this.SplitContainer.SuspendLayout();
            this.SelectedGroupBox.SuspendLayout();
            this.NoDupsGroupBox.SuspendLayout();
            this.DupsGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // GetResultsButton
            // 
            this.GetResultsButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.GetResultsButton.Location = new System.Drawing.Point(724, 518);
            this.GetResultsButton.Name = "GetResultsButton";
            this.GetResultsButton.Size = new System.Drawing.Size(75, 23);
            this.GetResultsButton.TabIndex = 1;
            this.GetResultsButton.Text = "Query";
            this.GetResultsButton.UseVisualStyleBackColor = true;
            this.GetResultsButton.Click += new System.EventHandler(this.GetResultsButton_Click);
            // 
            // label1
            // 
            this.label1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(5, 26);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(45, 13);
            this.label1.TabIndex = 5;
            this.label1.Text = "Passed:";
            // 
            // label2
            // 
            this.label2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(12, 39);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(38, 13);
            this.label2.TabIndex = 6;
            this.label2.Text = "Failed:";
            // 
            // label3
            // 
            this.label3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(104, 26);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(70, 13);
            this.label3.TabIndex = 7;
            this.label3.Text = "Inconclusive:";
            // 
            // label4
            // 
            this.label4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(1, 52);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(49, 13);
            this.label4.TabIndex = 8;
            this.label4.Text = "Blocked:";
            // 
            // label5
            // 
            this.label5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(125, 13);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(48, 13);
            this.label5.TabIndex = 9;
            this.label5.Text = "Queued:";
            // 
            // label6
            // 
            this.label6.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(137, 52);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(36, 13);
            this.label6.TabIndex = 10;
            this.label6.Text = "Other:";
            // 
            // PassedTotal
            // 
            this.PassedTotal.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.PassedTotal.AutoSize = true;
            this.PassedTotal.Location = new System.Drawing.Point(55, 26);
            this.PassedTotal.Name = "PassedTotal";
            this.PassedTotal.Size = new System.Drawing.Size(13, 13);
            this.PassedTotal.TabIndex = 12;
            this.PassedTotal.Text = "0";
            // 
            // OtherTotal
            // 
            this.OtherTotal.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.OtherTotal.AutoSize = true;
            this.OtherTotal.Location = new System.Drawing.Point(179, 52);
            this.OtherTotal.Name = "OtherTotal";
            this.OtherTotal.Size = new System.Drawing.Size(13, 13);
            this.OtherTotal.TabIndex = 14;
            this.OtherTotal.Text = "0";
            // 
            // InconclusiveTotal
            // 
            this.InconclusiveTotal.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.InconclusiveTotal.AutoSize = true;
            this.InconclusiveTotal.Location = new System.Drawing.Point(179, 26);
            this.InconclusiveTotal.Name = "InconclusiveTotal";
            this.InconclusiveTotal.Size = new System.Drawing.Size(13, 13);
            this.InconclusiveTotal.TabIndex = 15;
            this.InconclusiveTotal.Text = "0";
            // 
            // QueuedTotal
            // 
            this.QueuedTotal.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.QueuedTotal.AutoSize = true;
            this.QueuedTotal.Location = new System.Drawing.Point(179, 13);
            this.QueuedTotal.Name = "QueuedTotal";
            this.QueuedTotal.Size = new System.Drawing.Size(13, 13);
            this.QueuedTotal.TabIndex = 16;
            this.QueuedTotal.Text = "0";
            // 
            // BlockedTotal
            // 
            this.BlockedTotal.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BlockedTotal.AutoSize = true;
            this.BlockedTotal.Location = new System.Drawing.Point(55, 52);
            this.BlockedTotal.Name = "BlockedTotal";
            this.BlockedTotal.Size = new System.Drawing.Size(13, 13);
            this.BlockedTotal.TabIndex = 17;
            this.BlockedTotal.Text = "0";
            // 
            // FailedTotal
            // 
            this.FailedTotal.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.FailedTotal.AutoSize = true;
            this.FailedTotal.Location = new System.Drawing.Point(55, 39);
            this.FailedTotal.Name = "FailedTotal";
            this.FailedTotal.Size = new System.Drawing.Size(13, 13);
            this.FailedTotal.TabIndex = 18;
            this.FailedTotal.Text = "0";
            // 
            // SaveButton
            // 
            this.SaveButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.SaveButton.Enabled = false;
            this.SaveButton.Location = new System.Drawing.Point(724, 570);
            this.SaveButton.Name = "SaveButton";
            this.SaveButton.Size = new System.Drawing.Size(75, 23);
            this.SaveButton.TabIndex = 19;
            this.SaveButton.Text = "Save";
            this.SaveButton.UseVisualStyleBackColor = true;
            this.SaveButton.Click += new System.EventHandler(this.SaveButton_Click);
            // 
            // StructureView
            // 
            this.StructureView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.StructureView.ContextMenuStrip = this.UpdateResultsContextMenuStrip;
            this.StructureView.ImageIndex = 0;
            this.StructureView.ImageList = this.imageList;
            this.StructureView.Location = new System.Drawing.Point(3, 6);
            this.StructureView.Name = "StructureView";
            this.StructureView.SelectedImageIndex = 0;
            this.StructureView.Size = new System.Drawing.Size(241, 590);
            this.StructureView.TabIndex = 21;
            this.StructureView.NodeMouseClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.StructureView_NodeMouseClick);
            this.StructureView.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.StructureView_NodeMouseDoubleClick);
            // 
            // UpdateResultsContextMenuStrip
            // 
            this.UpdateResultsContextMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.GetResultsToolStripMenuItem,
            this.ExportToExcelToolStripMenuItem});
            this.UpdateResultsContextMenuStrip.Name = "UpdateResultsContextMenuStrip";
            this.UpdateResultsContextMenuStrip.Size = new System.Drawing.Size(153, 48);
            // 
            // GetResultsToolStripMenuItem
            // 
            this.GetResultsToolStripMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.GetResultsToolStripMenuItem.Name = "GetResultsToolStripMenuItem";
            this.GetResultsToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.GetResultsToolStripMenuItem.Text = "Update Results";
            this.GetResultsToolStripMenuItem.Click += new System.EventHandler(this.GetResultsToolStripMenuItem_Click);
            // 
            // ExportToExcelToolStripMenuItem
            // 
            this.ExportToExcelToolStripMenuItem.Name = "ExportToExcelToolStripMenuItem";
            this.ExportToExcelToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.ExportToExcelToolStripMenuItem.Text = "Export To Excel";
            this.ExportToExcelToolStripMenuItem.Click += new System.EventHandler(this.ExportToExcelToolStripMenuItem_Click);
            // 
            // imageList
            // 
            this.imageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList.ImageStream")));
            this.imageList.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList.Images.SetKeyName(0, "FolderIcon.ico");
            this.imageList.Images.SetKeyName(1, "TestIcon.ico");
            this.imageList.Images.SetKeyName(2, "ActiveIcon.ico");
            this.imageList.Images.SetKeyName(3, "OKIcon.ico");
            this.imageList.Images.SetKeyName(4, "ErrorIcon.ico");
            this.imageList.Images.SetKeyName(5, "WarningIcon.ico");
            this.imageList.Images.SetKeyName(6, "BlockedIcon.ico");
            this.imageList.Images.SetKeyName(7, "InProgressIcon.ico");
            this.imageList.Images.SetKeyName(8, "UnknownIcon.ico");
            // 
            // statusStrip
            // 
            this.statusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ToolStripStatusLabel,
            this.ToolStripStatusBusy,
            this.ToolStripStatusLabelSpring,
            this.toolStripStatusUpdatedLabel,
            this.ToolStripStatusLastUpdate});
            this.statusStrip.Location = new System.Drawing.Point(0, 603);
            this.statusStrip.Name = "statusStrip";
            this.statusStrip.Size = new System.Drawing.Size(1073, 22);
            this.statusStrip.TabIndex = 23;
            this.statusStrip.Text = "statusStrip1";
            // 
            // ToolStripStatusLabel
            // 
            this.ToolStripStatusLabel.Name = "ToolStripStatusLabel";
            this.ToolStripStatusLabel.Size = new System.Drawing.Size(0, 17);
            // 
            // ToolStripStatusBusy
            // 
            this.ToolStripStatusBusy.Image = ((System.Drawing.Image)(resources.GetObject("ToolStripStatusBusy.Image")));
            this.ToolStripStatusBusy.Name = "ToolStripStatusBusy";
            this.ToolStripStatusBusy.Size = new System.Drawing.Size(16, 17);
            this.ToolStripStatusBusy.Visible = false;
            // 
            // ToolStripStatusLabelSpring
            // 
            this.ToolStripStatusLabelSpring.Name = "ToolStripStatusLabelSpring";
            this.ToolStripStatusLabelSpring.Size = new System.Drawing.Size(952, 17);
            this.ToolStripStatusLabelSpring.Spring = true;
            // 
            // toolStripStatusUpdatedLabel
            // 
            this.toolStripStatusUpdatedLabel.Name = "toolStripStatusUpdatedLabel";
            this.toolStripStatusUpdatedLabel.Size = new System.Drawing.Size(82, 17);
            this.toolStripStatusUpdatedLabel.Text = "Last Updated: ";
            // 
            // ToolStripStatusLastUpdate
            // 
            this.ToolStripStatusLastUpdate.Name = "ToolStripStatusLastUpdate";
            this.ToolStripStatusLastUpdate.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ToolStripStatusLastUpdate.Size = new System.Drawing.Size(24, 17);
            this.ToolStripStatusLastUpdate.Text = "NA";
            this.ToolStripStatusLastUpdate.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            // 
            // SplitContainer
            // 
            this.SplitContainer.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.SplitContainer.Location = new System.Drawing.Point(12, 1);
            this.SplitContainer.Name = "SplitContainer";
            // 
            // SplitContainer.Panel1
            // 
            this.SplitContainer.Panel1.Controls.Add(this.StructureView);
            // 
            // SplitContainer.Panel2
            // 
            this.SplitContainer.Panel2.Controls.Add(this.SelectedGroupBox);
            this.SplitContainer.Panel2.Controls.Add(this.SwitchPlanButton);
            this.SplitContainer.Panel2.Controls.Add(this.SaveButton);
            this.SplitContainer.Panel2.Controls.Add(this.GetResultsButton);
            this.SplitContainer.Panel2.Controls.Add(this.NoDupsGroupBox);
            this.SplitContainer.Panel2.Controls.Add(this.DupsGroupBox);
            this.SplitContainer.Panel2.Controls.Add(this.ResultsListView);
            this.SplitContainer.Panel2MinSize = 700;
            this.SplitContainer.Size = new System.Drawing.Size(1058, 599);
            this.SplitContainer.SplitterDistance = 246;
            this.SplitContainer.TabIndex = 24;
            // 
            // SelectedGroupBox
            // 
            this.SelectedGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.SelectedGroupBox.Controls.Add(this.ActiveSelectedLabel);
            this.SelectedGroupBox.Controls.Add(this.label17);
            this.SelectedGroupBox.Controls.Add(this.NotExecutedSelectedLabel);
            this.SelectedGroupBox.Controls.Add(this.label21);
            this.SelectedGroupBox.Controls.Add(this.label23);
            this.SelectedGroupBox.Controls.Add(this.TotalSelectedLabel);
            this.SelectedGroupBox.Controls.Add(this.label25);
            this.SelectedGroupBox.Controls.Add(this.label26);
            this.SelectedGroupBox.Controls.Add(this.label27);
            this.SelectedGroupBox.Controls.Add(this.InconclusiveSelectedLabel);
            this.SelectedGroupBox.Controls.Add(this.QueuedSelectedLabel);
            this.SelectedGroupBox.Controls.Add(this.OtherSelectedLabel);
            this.SelectedGroupBox.Controls.Add(this.label31);
            this.SelectedGroupBox.Controls.Add(this.label32);
            this.SelectedGroupBox.Controls.Add(this.FailedSelectedLabel);
            this.SelectedGroupBox.Controls.Add(this.label34);
            this.SelectedGroupBox.Controls.Add(this.PassedSelectedLabel);
            this.SelectedGroupBox.Controls.Add(this.BlockedSelectedLabel);
            this.SelectedGroupBox.Location = new System.Drawing.Point(458, 515);
            this.SelectedGroupBox.Name = "SelectedGroupBox";
            this.SelectedGroupBox.Size = new System.Drawing.Size(220, 81);
            this.SelectedGroupBox.TabIndex = 65;
            this.SelectedGroupBox.TabStop = false;
            this.SelectedGroupBox.Text = "Selected";
            // 
            // ActiveSelectedLabel
            // 
            this.ActiveSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ActiveSelectedLabel.AutoSize = true;
            this.ActiveSelectedLabel.Location = new System.Drawing.Point(56, 65);
            this.ActiveSelectedLabel.Name = "ActiveSelectedLabel";
            this.ActiveSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.ActiveSelectedLabel.TabIndex = 64;
            this.ActiveSelectedLabel.Text = "0";
            // 
            // label17
            // 
            this.label17.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label17.AutoSize = true;
            this.label17.Location = new System.Drawing.Point(10, 65);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(40, 13);
            this.label17.TabIndex = 63;
            this.label17.Text = "Active:";
            // 
            // NotExecutedSelectedLabel
            // 
            this.NotExecutedSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.NotExecutedSelectedLabel.AutoSize = true;
            this.NotExecutedSelectedLabel.Location = new System.Drawing.Point(179, 39);
            this.NotExecutedSelectedLabel.Name = "NotExecutedSelectedLabel";
            this.NotExecutedSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.NotExecutedSelectedLabel.TabIndex = 62;
            this.NotExecutedSelectedLabel.Text = "0";
            // 
            // label21
            // 
            this.label21.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label21.AutoSize = true;
            this.label21.Location = new System.Drawing.Point(86, 39);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(87, 13);
            this.label21.TabIndex = 61;
            this.label21.Text = "Never Executed:";
            // 
            // label23
            // 
            this.label23.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label23.AutoSize = true;
            this.label23.Location = new System.Drawing.Point(17, 13);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(34, 13);
            this.label23.TabIndex = 59;
            this.label23.Text = "Total:";
            // 
            // TotalSelectedLabel
            // 
            this.TotalSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.TotalSelectedLabel.AutoSize = true;
            this.TotalSelectedLabel.Location = new System.Drawing.Point(56, 13);
            this.TotalSelectedLabel.Name = "TotalSelectedLabel";
            this.TotalSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.TotalSelectedLabel.TabIndex = 60;
            this.TotalSelectedLabel.Text = "0";
            // 
            // label25
            // 
            this.label25.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label25.AutoSize = true;
            this.label25.Location = new System.Drawing.Point(13, 39);
            this.label25.Name = "label25";
            this.label25.Size = new System.Drawing.Size(38, 13);
            this.label25.TabIndex = 48;
            this.label25.Text = "Failed:";
            // 
            // label26
            // 
            this.label26.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label26.AutoSize = true;
            this.label26.Location = new System.Drawing.Point(6, 26);
            this.label26.Name = "label26";
            this.label26.Size = new System.Drawing.Size(45, 13);
            this.label26.TabIndex = 47;
            this.label26.Text = "Passed:";
            // 
            // label27
            // 
            this.label27.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label27.AutoSize = true;
            this.label27.Location = new System.Drawing.Point(2, 52);
            this.label27.Name = "label27";
            this.label27.Size = new System.Drawing.Size(49, 13);
            this.label27.TabIndex = 50;
            this.label27.Text = "Blocked:";
            // 
            // InconclusiveSelectedLabel
            // 
            this.InconclusiveSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.InconclusiveSelectedLabel.AutoSize = true;
            this.InconclusiveSelectedLabel.Location = new System.Drawing.Point(179, 26);
            this.InconclusiveSelectedLabel.Name = "InconclusiveSelectedLabel";
            this.InconclusiveSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.InconclusiveSelectedLabel.TabIndex = 55;
            this.InconclusiveSelectedLabel.Text = "0";
            // 
            // QueuedSelectedLabel
            // 
            this.QueuedSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.QueuedSelectedLabel.AutoSize = true;
            this.QueuedSelectedLabel.Location = new System.Drawing.Point(179, 13);
            this.QueuedSelectedLabel.Name = "QueuedSelectedLabel";
            this.QueuedSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.QueuedSelectedLabel.TabIndex = 56;
            this.QueuedSelectedLabel.Text = "0";
            // 
            // OtherSelectedLabel
            // 
            this.OtherSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.OtherSelectedLabel.AutoSize = true;
            this.OtherSelectedLabel.Location = new System.Drawing.Point(179, 52);
            this.OtherSelectedLabel.Name = "OtherSelectedLabel";
            this.OtherSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.OtherSelectedLabel.TabIndex = 54;
            this.OtherSelectedLabel.Text = "0";
            // 
            // label31
            // 
            this.label31.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label31.AutoSize = true;
            this.label31.Location = new System.Drawing.Point(125, 13);
            this.label31.Name = "label31";
            this.label31.Size = new System.Drawing.Size(48, 13);
            this.label31.TabIndex = 51;
            this.label31.Text = "Queued:";
            // 
            // label32
            // 
            this.label32.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label32.AutoSize = true;
            this.label32.Location = new System.Drawing.Point(137, 52);
            this.label32.Name = "label32";
            this.label32.Size = new System.Drawing.Size(36, 13);
            this.label32.TabIndex = 52;
            this.label32.Text = "Other:";
            // 
            // FailedSelectedLabel
            // 
            this.FailedSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.FailedSelectedLabel.AutoSize = true;
            this.FailedSelectedLabel.Location = new System.Drawing.Point(56, 39);
            this.FailedSelectedLabel.Name = "FailedSelectedLabel";
            this.FailedSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.FailedSelectedLabel.TabIndex = 58;
            this.FailedSelectedLabel.Text = "0";
            // 
            // label34
            // 
            this.label34.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label34.AutoSize = true;
            this.label34.Location = new System.Drawing.Point(104, 26);
            this.label34.Name = "label34";
            this.label34.Size = new System.Drawing.Size(70, 13);
            this.label34.TabIndex = 49;
            this.label34.Text = "Inconclusive:";
            // 
            // PassedSelectedLabel
            // 
            this.PassedSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.PassedSelectedLabel.AutoSize = true;
            this.PassedSelectedLabel.Location = new System.Drawing.Point(56, 26);
            this.PassedSelectedLabel.Name = "PassedSelectedLabel";
            this.PassedSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.PassedSelectedLabel.TabIndex = 53;
            this.PassedSelectedLabel.Text = "0";
            // 
            // BlockedSelectedLabel
            // 
            this.BlockedSelectedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BlockedSelectedLabel.AutoSize = true;
            this.BlockedSelectedLabel.Location = new System.Drawing.Point(56, 52);
            this.BlockedSelectedLabel.Name = "BlockedSelectedLabel";
            this.BlockedSelectedLabel.Size = new System.Drawing.Size(13, 13);
            this.BlockedSelectedLabel.TabIndex = 57;
            this.BlockedSelectedLabel.Text = "0";
            // 
            // SwitchPlanButton
            // 
            this.SwitchPlanButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.SwitchPlanButton.Enabled = false;
            this.SwitchPlanButton.Location = new System.Drawing.Point(724, 544);
            this.SwitchPlanButton.Name = "SwitchPlanButton";
            this.SwitchPlanButton.Size = new System.Drawing.Size(75, 23);
            this.SwitchPlanButton.TabIndex = 26;
            this.SwitchPlanButton.Text = "Switch Plan";
            this.SwitchPlanButton.UseVisualStyleBackColor = true;
            this.SwitchPlanButton.Click += new System.EventHandler(this.SwitchPlanButton_Click);
            // 
            // NoDupsGroupBox
            // 
            this.NoDupsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.NoDupsGroupBox.Controls.Add(this.ActiveNonDupLabel);
            this.NoDupsGroupBox.Controls.Add(this.label16);
            this.NoDupsGroupBox.Controls.Add(this.NeverExecutedNonDupLabel);
            this.NoDupsGroupBox.Controls.Add(this.label10);
            this.NoDupsGroupBox.Controls.Add(this.label11);
            this.NoDupsGroupBox.Controls.Add(this.TotalNonDupLabel);
            this.NoDupsGroupBox.Controls.Add(this.label13);
            this.NoDupsGroupBox.Controls.Add(this.label14);
            this.NoDupsGroupBox.Controls.Add(this.label15);
            this.NoDupsGroupBox.Controls.Add(this.InconclusiveNonDupLabel);
            this.NoDupsGroupBox.Controls.Add(this.QueuedNonDupLabel);
            this.NoDupsGroupBox.Controls.Add(this.OtherNonDupLabel);
            this.NoDupsGroupBox.Controls.Add(this.label19);
            this.NoDupsGroupBox.Controls.Add(this.label20);
            this.NoDupsGroupBox.Controls.Add(this.FailedNonDupLabel);
            this.NoDupsGroupBox.Controls.Add(this.label22);
            this.NoDupsGroupBox.Controls.Add(this.PassedNonDupLabel);
            this.NoDupsGroupBox.Controls.Add(this.BlockedNonDupLabel);
            this.NoDupsGroupBox.Location = new System.Drawing.Point(232, 515);
            this.NoDupsGroupBox.Name = "NoDupsGroupBox";
            this.NoDupsGroupBox.Size = new System.Drawing.Size(220, 81);
            this.NoDupsGroupBox.TabIndex = 48;
            this.NoDupsGroupBox.TabStop = false;
            this.NoDupsGroupBox.Text = "Total without duplicates";
            // 
            // ActiveNonDupLabel
            // 
            this.ActiveNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ActiveNonDupLabel.AutoSize = true;
            this.ActiveNonDupLabel.Location = new System.Drawing.Point(56, 65);
            this.ActiveNonDupLabel.Name = "ActiveNonDupLabel";
            this.ActiveNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.ActiveNonDupLabel.TabIndex = 64;
            this.ActiveNonDupLabel.Text = "0";
            // 
            // label16
            // 
            this.label16.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label16.AutoSize = true;
            this.label16.Location = new System.Drawing.Point(10, 65);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(40, 13);
            this.label16.TabIndex = 63;
            this.label16.Text = "Active:";
            // 
            // NeverExecutedNonDupLabel
            // 
            this.NeverExecutedNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.NeverExecutedNonDupLabel.AutoSize = true;
            this.NeverExecutedNonDupLabel.Location = new System.Drawing.Point(179, 39);
            this.NeverExecutedNonDupLabel.Name = "NeverExecutedNonDupLabel";
            this.NeverExecutedNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.NeverExecutedNonDupLabel.TabIndex = 62;
            this.NeverExecutedNonDupLabel.Text = "0";
            // 
            // label10
            // 
            this.label10.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(86, 39);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(87, 13);
            this.label10.TabIndex = 61;
            this.label10.Text = "Never Executed:";
            // 
            // label11
            // 
            this.label11.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(17, 13);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(34, 13);
            this.label11.TabIndex = 59;
            this.label11.Text = "Total:";
            // 
            // TotalNonDupLabel
            // 
            this.TotalNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.TotalNonDupLabel.AutoSize = true;
            this.TotalNonDupLabel.Location = new System.Drawing.Point(56, 13);
            this.TotalNonDupLabel.Name = "TotalNonDupLabel";
            this.TotalNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.TotalNonDupLabel.TabIndex = 60;
            this.TotalNonDupLabel.Text = "0";
            // 
            // label13
            // 
            this.label13.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(13, 39);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(38, 13);
            this.label13.TabIndex = 48;
            this.label13.Text = "Failed:";
            // 
            // label14
            // 
            this.label14.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(6, 26);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(45, 13);
            this.label14.TabIndex = 47;
            this.label14.Text = "Passed:";
            // 
            // label15
            // 
            this.label15.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(2, 52);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(49, 13);
            this.label15.TabIndex = 50;
            this.label15.Text = "Blocked:";
            // 
            // InconclusiveNonDupLabel
            // 
            this.InconclusiveNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.InconclusiveNonDupLabel.AutoSize = true;
            this.InconclusiveNonDupLabel.Location = new System.Drawing.Point(179, 26);
            this.InconclusiveNonDupLabel.Name = "InconclusiveNonDupLabel";
            this.InconclusiveNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.InconclusiveNonDupLabel.TabIndex = 55;
            this.InconclusiveNonDupLabel.Text = "0";
            // 
            // QueuedNonDupLabel
            // 
            this.QueuedNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.QueuedNonDupLabel.AutoSize = true;
            this.QueuedNonDupLabel.Location = new System.Drawing.Point(179, 13);
            this.QueuedNonDupLabel.Name = "QueuedNonDupLabel";
            this.QueuedNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.QueuedNonDupLabel.TabIndex = 56;
            this.QueuedNonDupLabel.Text = "0";
            // 
            // OtherNonDupLabel
            // 
            this.OtherNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.OtherNonDupLabel.AutoSize = true;
            this.OtherNonDupLabel.Location = new System.Drawing.Point(179, 52);
            this.OtherNonDupLabel.Name = "OtherNonDupLabel";
            this.OtherNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.OtherNonDupLabel.TabIndex = 54;
            this.OtherNonDupLabel.Text = "0";
            // 
            // label19
            // 
            this.label19.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label19.AutoSize = true;
            this.label19.Location = new System.Drawing.Point(125, 13);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(48, 13);
            this.label19.TabIndex = 51;
            this.label19.Text = "Queued:";
            // 
            // label20
            // 
            this.label20.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label20.AutoSize = true;
            this.label20.Location = new System.Drawing.Point(137, 52);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(36, 13);
            this.label20.TabIndex = 52;
            this.label20.Text = "Other:";
            // 
            // FailedNonDupLabel
            // 
            this.FailedNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.FailedNonDupLabel.AutoSize = true;
            this.FailedNonDupLabel.Location = new System.Drawing.Point(56, 39);
            this.FailedNonDupLabel.Name = "FailedNonDupLabel";
            this.FailedNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.FailedNonDupLabel.TabIndex = 58;
            this.FailedNonDupLabel.Text = "0";
            // 
            // label22
            // 
            this.label22.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label22.AutoSize = true;
            this.label22.Location = new System.Drawing.Point(104, 26);
            this.label22.Name = "label22";
            this.label22.Size = new System.Drawing.Size(70, 13);
            this.label22.TabIndex = 49;
            this.label22.Text = "Inconclusive:";
            // 
            // PassedNonDupLabel
            // 
            this.PassedNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.PassedNonDupLabel.AutoSize = true;
            this.PassedNonDupLabel.Location = new System.Drawing.Point(56, 26);
            this.PassedNonDupLabel.Name = "PassedNonDupLabel";
            this.PassedNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.PassedNonDupLabel.TabIndex = 53;
            this.PassedNonDupLabel.Text = "0";
            // 
            // BlockedNonDupLabel
            // 
            this.BlockedNonDupLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BlockedNonDupLabel.AutoSize = true;
            this.BlockedNonDupLabel.Location = new System.Drawing.Point(56, 52);
            this.BlockedNonDupLabel.Name = "BlockedNonDupLabel";
            this.BlockedNonDupLabel.Size = new System.Drawing.Size(13, 13);
            this.BlockedNonDupLabel.TabIndex = 57;
            this.BlockedNonDupLabel.Text = "0";
            // 
            // DupsGroupBox
            // 
            this.DupsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.DupsGroupBox.Controls.Add(this.ActiveTotal);
            this.DupsGroupBox.Controls.Add(this.label12);
            this.DupsGroupBox.Controls.Add(this.label9);
            this.DupsGroupBox.Controls.Add(this.BlockedTotal);
            this.DupsGroupBox.Controls.Add(this.PassedTotal);
            this.DupsGroupBox.Controls.Add(this.label3);
            this.DupsGroupBox.Controls.Add(this.FailedTotal);
            this.DupsGroupBox.Controls.Add(this.label6);
            this.DupsGroupBox.Controls.Add(this.label5);
            this.DupsGroupBox.Controls.Add(this.OtherTotal);
            this.DupsGroupBox.Controls.Add(this.QueuedTotal);
            this.DupsGroupBox.Controls.Add(this.InconclusiveTotal);
            this.DupsGroupBox.Controls.Add(this.label4);
            this.DupsGroupBox.Controls.Add(this.label1);
            this.DupsGroupBox.Controls.Add(this.label2);
            this.DupsGroupBox.Controls.Add(this.TotalLabel);
            this.DupsGroupBox.Controls.Add(this.label7);
            this.DupsGroupBox.Controls.Add(this.NeverExecuted);
            this.DupsGroupBox.Location = new System.Drawing.Point(6, 515);
            this.DupsGroupBox.Name = "DupsGroupBox";
            this.DupsGroupBox.Size = new System.Drawing.Size(220, 81);
            this.DupsGroupBox.TabIndex = 47;
            this.DupsGroupBox.TabStop = false;
            this.DupsGroupBox.Text = "Total with duplicates";
            // 
            // ActiveTotal
            // 
            this.ActiveTotal.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ActiveTotal.AutoSize = true;
            this.ActiveTotal.Location = new System.Drawing.Point(55, 65);
            this.ActiveTotal.Name = "ActiveTotal";
            this.ActiveTotal.Size = new System.Drawing.Size(13, 13);
            this.ActiveTotal.TabIndex = 32;
            this.ActiveTotal.Text = "0";
            // 
            // label12
            // 
            this.label12.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(9, 65);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(40, 13);
            this.label12.TabIndex = 31;
            this.label12.Text = "Active:";
            // 
            // label9
            // 
            this.label9.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(86, 39);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(87, 13);
            this.label9.TabIndex = 29;
            this.label9.Text = "Never Executed:";
            // 
            // TotalLabel
            // 
            this.TotalLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.TotalLabel.AutoSize = true;
            this.TotalLabel.Location = new System.Drawing.Point(55, 13);
            this.TotalLabel.Name = "TotalLabel";
            this.TotalLabel.Size = new System.Drawing.Size(13, 13);
            this.TotalLabel.TabIndex = 25;
            this.TotalLabel.Text = "0";
            // 
            // label7
            // 
            this.label7.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(16, 13);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(34, 13);
            this.label7.TabIndex = 24;
            this.label7.Text = "Total:";
            // 
            // NeverExecuted
            // 
            this.NeverExecuted.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.NeverExecuted.AutoSize = true;
            this.NeverExecuted.Location = new System.Drawing.Point(179, 39);
            this.NeverExecuted.Name = "NeverExecuted";
            this.NeverExecuted.Size = new System.Drawing.Size(13, 13);
            this.NeverExecuted.TabIndex = 30;
            this.NeverExecuted.Text = "0";
            // 
            // ResultsListView
            // 
            this.ResultsListView.AllowColumnReorder = true;
            this.ResultsListView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ResultsListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.OutcomeHeader,
            this.StateHeader,
            this.IDHeader,
            this.NameHeader,
            this.PathHeader,
            this.PriorityHeader,
            this.CompletedHeader,
            this.IsAutomatedHeader,
            this.TestCaseAreaHeader,
            this.ConfigHeader,
            this.FailureHeader,
            this.ErrorMessageHeader,
            this.HistoricHeader});
            this.ResultsListView.FullRowSelect = true;
            this.ResultsListView.GridLines = true;
            this.ResultsListView.LargeImageList = this.imageList;
            this.ResultsListView.Location = new System.Drawing.Point(6, 6);
            this.ResultsListView.Name = "ResultsListView";
            this.ResultsListView.Size = new System.Drawing.Size(794, 503);
            this.ResultsListView.SmallImageList = this.imageList;
            this.ResultsListView.Sorting = System.Windows.Forms.SortOrder.Ascending;
            this.ResultsListView.TabIndex = 28;
            this.ResultsListView.UseCompatibleStateImageBehavior = false;
            this.ResultsListView.View = System.Windows.Forms.View.Details;
            this.ResultsListView.ColumnClick += new System.Windows.Forms.ColumnClickEventHandler(this.ResultsListView_ColumnClick);
            this.ResultsListView.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ResultsListView_KeyDown);
            this.ResultsListView.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.ResultsListView_MouseDoubleClick);
            // 
            // OutcomeHeader
            // 
            this.OutcomeHeader.Text = "Outcome";
            this.OutcomeHeader.Width = 55;
            // 
            // StateHeader
            // 
            this.StateHeader.Text = "State";
            this.StateHeader.Width = 50;
            // 
            // IDHeader
            // 
            this.IDHeader.Text = "ID";
            this.IDHeader.Width = 45;
            // 
            // NameHeader
            // 
            this.NameHeader.Text = "Name";
            this.NameHeader.Width = 80;
            // 
            // PathHeader
            // 
            this.PathHeader.Text = "Path";
            // 
            // PriorityHeader
            // 
            this.PriorityHeader.Text = "Priority";
            this.PriorityHeader.Width = 44;
            // 
            // CompletedHeader
            // 
            this.CompletedHeader.Text = "Completed";
            // 
            // IsAutomatedHeader
            // 
            this.IsAutomatedHeader.Text = "Automated";
            this.IsAutomatedHeader.Width = 55;
            // 
            // TestCaseAreaHeader
            // 
            this.TestCaseAreaHeader.Text = "Area";
            // 
            // FailureHeader
            // 
            this.FailureHeader.Text = "Failure Type";
            this.FailureHeader.Width = 69;
            // 
            // ErrorMessageHeader
            // 
            this.ErrorMessageHeader.Text = "Error Message";
            this.ErrorMessageHeader.Width = 86;
            // 
            // HistoricHeader
            // 
            this.HistoricHeader.Text = "Recent History (*most recent first)";
            this.HistoricHeader.Width = 65;
            // 
            // ConfigHeader
            // 
            this.ConfigHeader.Text = "Configuration";
            // 
            // PlanUI
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1073, 625);
            this.Controls.Add(this.statusStrip);
            this.Controls.Add(this.SplitContainer);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(1089, 250);
            this.Name = "PlanUI";
            this.Text = "Test Plan Viewer";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.TestResultUI_FormClosing);
            this.UpdateResultsContextMenuStrip.ResumeLayout(false);
            this.statusStrip.ResumeLayout(false);
            this.statusStrip.PerformLayout();
            this.SplitContainer.Panel1.ResumeLayout(false);
            this.SplitContainer.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.SplitContainer)).EndInit();
            this.SplitContainer.ResumeLayout(false);
            this.SelectedGroupBox.ResumeLayout(false);
            this.SelectedGroupBox.PerformLayout();
            this.NoDupsGroupBox.ResumeLayout(false);
            this.NoDupsGroupBox.PerformLayout();
            this.DupsGroupBox.ResumeLayout(false);
            this.DupsGroupBox.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button GetResultsButton;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label PassedTotal;
        private System.Windows.Forms.Label OtherTotal;
        private System.Windows.Forms.Label InconclusiveTotal;
        private System.Windows.Forms.Label QueuedTotal;
        private System.Windows.Forms.Label BlockedTotal;
        private System.Windows.Forms.Label FailedTotal;
        private System.Windows.Forms.Button SaveButton;
        private System.Windows.Forms.TreeView StructureView;
        private System.Windows.Forms.ImageList imageList;
        private System.Windows.Forms.ContextMenuStrip UpdateResultsContextMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem GetResultsToolStripMenuItem;
        private System.Windows.Forms.StatusStrip statusStrip;
        private System.Windows.Forms.ToolStripStatusLabel ToolStripStatusLabel;
        private System.Windows.Forms.SplitContainer SplitContainer;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label TotalLabel;
        private System.Windows.Forms.ToolStripStatusLabel ToolStripStatusLastUpdate;
        private System.Windows.Forms.ToolStripStatusLabel ToolStripStatusLabelSpring;
        private System.Windows.Forms.ToolStripStatusLabel ToolStripStatusBusy;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusUpdatedLabel;
        private System.Windows.Forms.Button SwitchPlanButton;
        private System.Windows.Forms.ListView ResultsListView;
        private System.Windows.Forms.ColumnHeader OutcomeHeader;
        private System.Windows.Forms.ColumnHeader IDHeader;
        private System.Windows.Forms.ColumnHeader NameHeader;
        private System.Windows.Forms.ColumnHeader PathHeader;
        private System.Windows.Forms.ColumnHeader PriorityHeader;
        private System.Windows.Forms.ColumnHeader CompletedHeader;
        private System.Windows.Forms.ColumnHeader IsAutomatedHeader;
        private System.Windows.Forms.ColumnHeader TestCaseAreaHeader;
        private System.Windows.Forms.ColumnHeader FailureHeader;
        private System.Windows.Forms.ColumnHeader ErrorMessageHeader;
        private System.Windows.Forms.Label NeverExecuted;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.ToolStripMenuItem ExportToExcelToolStripMenuItem;
        private System.Windows.Forms.GroupBox NoDupsGroupBox;
        private System.Windows.Forms.Label NeverExecutedNonDupLabel;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label TotalNonDupLabel;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label InconclusiveNonDupLabel;
        private System.Windows.Forms.Label QueuedNonDupLabel;
        private System.Windows.Forms.Label OtherNonDupLabel;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.Label FailedNonDupLabel;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Label PassedNonDupLabel;
        private System.Windows.Forms.Label BlockedNonDupLabel;
        private System.Windows.Forms.GroupBox DupsGroupBox;
        private System.Windows.Forms.ColumnHeader StateHeader;
        private System.Windows.Forms.Label ActiveNonDupLabel;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label ActiveTotal;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.ColumnHeader HistoricHeader;
        private System.Windows.Forms.GroupBox SelectedGroupBox;
        private System.Windows.Forms.Label ActiveSelectedLabel;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label NotExecutedSelectedLabel;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.Label TotalSelectedLabel;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.Label label26;
        private System.Windows.Forms.Label label27;
        private System.Windows.Forms.Label InconclusiveSelectedLabel;
        private System.Windows.Forms.Label QueuedSelectedLabel;
        private System.Windows.Forms.Label OtherSelectedLabel;
        private System.Windows.Forms.Label label31;
        private System.Windows.Forms.Label label32;
        private System.Windows.Forms.Label FailedSelectedLabel;
        private System.Windows.Forms.Label label34;
        private System.Windows.Forms.Label PassedSelectedLabel;
        private System.Windows.Forms.Label BlockedSelectedLabel;
        private System.Windows.Forms.ColumnHeader ConfigHeader;
    }
}

